/**
 * Flowtype definitions for util.ts
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.9.2
 */

export type Constructor = (...args: any[]) => any;
export type Func = (...args: any[]) => any;
declare export var instanceOfAny: any; // /* NO PRINT IMPLEMENTED: ArrowFunction */ any
