import { setupI18n } from '@lingui/core'

// messages.js is generated by the cli
import englishMessages from 'i18n/lingui/locales/en/messages.js'

// setup the i18n object with active language and catalogs
export const i18n = setupI18n({
  language: 'en',
  catalogs: {
    en: englishMessages,
  },
})
