const storageKeys = {
  CURRENCIES: 'JWALLET-CURRENCIES',
  CURRENCIES_CURRENT: 'JWALLET-CURRENCIES-CURRENT',
  CURRENCIES_BALANCES: 'JWALLET-CURRENCIES-BALANCES',
  NETWORKS: 'JWALLET-NETWORKS',
  NETWORKS_CURRENT: 'JWALLET-NETWORKS-CURRENT',
}

export default storageKeys
