// @flow strict

import { MAINNET } from 'data/networks'

import { configureStore } from './configureStore'
import {
  start,
} from './modules/core'
import {
  setCurrentNetwork,
  setCurrentAddress,
  setCurrentAssets,
} from './modules/config'

const store = configureStore()

store.dispatch(setCurrentNetwork(MAINNET))
store.dispatch(setCurrentAddress('0x6b05dD32BDCC1C162D0e3141D9e270c4d4A09918'))

store.dispatch(setCurrentAssets(
  {
    Ethereum: {
      name: 'Ethereum',
      symbol: 'ETH',
      blockchainParams: {
        address: 'Ethereum',
        type: 'ethereum',
        decimals: 18,
        staticGasAmount: 21000,
        deploymentBlockNumber: 0,
      },
      display: {
        isDefaultForcedDisplay: true,
        digitalAssetsListPriority: 1050,
      },
      assetPage: {
        // eslint-disable-next-line max-len
        description: 'Ether is a cryptocurrency whose blockchain is generated by the Ethereum platform. Ether can be transferred between accounts and used to compensate participant mining nodes for computations performed. Ethereum provides a decentralized Turing-complete virtual machine, the Ethereum Virtual Machine (EVM), which can execute scripts using an international network of public nodes. "Gas", an internal transaction pricing mechanism, is used to mitigate spam and allocate resources on the network.',
        urls: [
          {
            type: 'site',
            url: 'https://www.ethereum.org/',
          },
          {
            type: 'binance',
            url: 'https://info.binance.com/en/currencies/ethereum',
          },
          {
            type: 'coinmarketcap',
            url: 'https://coinmarketcap.com/currencies/ethereum',
          },
        ],
      },
      priceFeed: {
        currencyID: 1027,
        currencyIDType: 'coinmarketcap',
      },
      isActive: true,
      isCustom: false,
    },
    '0xa5Fd1A791C4dfcaacC963D4F73c6Ae5824149eA7': {
      name: 'Jibrel Network Token',
      symbol: 'JNT',
      blockchainParams: {
        type: 'erc-20',
        features: [
          'mintable',
        ],
        address: '0xa5Fd1A791C4dfcaacC963D4F73c6Ae5824149eA7',
        decimals: 18,
        staticGasAmount: 98232,
        deploymentBlockNumber: 4736154,
      },
      display: {
        isDefaultForcedDisplay: true,
        digitalAssetsListPriority: 980,
      },
      priceFeed: {
        currencyID: 2498,
        currencyIDType: 'coinmarketcap',
      },
      assetPage: {
        // eslint-disable-next-line max-len
        description: 'Jibrel provides currencies, equities, commodities and other financial assets as standard ERC-20 tokens on the Ethereum blockchain',
        urls: [
          {
            type: 'site',
            url: 'https://jibrel.network/',
          },
          {
            type: 'binance',
            url: 'https://info.binance.com/en/currencies/jibrel-network-token',
          },
          {
            type: 'coinmarketcap',
            url: 'https://coinmarketcap.com/currencies/jibrel-network',
          },
        ],
      },
      isActive: true,
      isCustom: false,
    },
  },
))

store.dispatch(start())
